### PR TITLE
Add autoPingInterval and autoPingTimeout

### PR DESCRIPTION
**Pull request by ghost**
This makes the connection more robust. Previously, a dropped connection would not be detected until the client attempts to send a message. For a "read-only" client that only listens to server messages, the dropped connection would never be detected.

With autoPingInterval and autoPingTimeout added, this is no longer an issue. I tested this change in a broadcaster-listener setup using iptables to artificially block packets.

See: http://nicolovaligi.com/automatic-reconnection-websockets-autobahn.html

### CODE REVIEW

**Comment by leameow** [comment]
Nice catch, would you mind to rebase? It conflicts with your previous PR.

**Comment by ghost** [comment]
Sure thing, just a minute.

**Comment by ghost** [comment]
Done

**Comment by leameow** [comment]
Cool, thanks for the cleanup!

**Pull request merged**
